refactor(ad_api_visualizers):rework parameter
autowarefoundation/autoware_universe pull request #8690
Opened 2024-08-30 07:20 UTC by prakash-kannaiah

### Description
----------------------------------------------
Implement the ROS Node configuration layout described in [Autoware Foundation Discussion #3371](https://github.com/orgs/autowarefoundation/discussions/3371) for the `ad_api_visualizers` package.

- Remove duplication of parameter declaration between the source code and the parameter file.
- Remove the default value from the source code to ensure all parameter values are passed from the parameter files.
- Use types that match those returned from declare_parameter() to prevent confusion and potential coding errors.
- Move the default parameter file to a standardized location. Use the JSON Schema for that.

### Tests performed
----------------------------------------------
Package built locally with `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to ad_api_visualizers`

### Pre-review checklist for the PR author
----------------------------------------------
The PR author must check the checkboxes below when creating the PR.

- [ ]  I've confirmed the [contribution guideline](https://autowarefoundation.github.io/autoware-documentation/main/contributing/).
- [ ]  The PR follows the pull [request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).

### In-review checklist for the PR reviewers
----------------------------------------------
The PR reviewers must check the checkboxes below before approval.

- [ ]  The PR follows the pull [request guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/).
- [ ]  The PR has been properly tested.
- [ ]  The PR has been reviewed by the code owners.

### Post-review checklist for the PR author
----------------------------------------------
The PR author must check the checkboxes below before merging.

- [ ]  There are no open discussions or they are tracked via tickets.
- [ ]  The PR is ready for merge.

After all checkboxes are checked, anyone with write access can merge the PR.

2024-09-01 13:01 UTC, yukkysaito approved these changes
LGTM

2024-09-02 04:49 UTC, isamu-takagi commented on system/default_ad_api_helpers/ad_api_visualizers/launch/ad_api_visualizers.launch.xml
> +    <param name="$(var param_path)"/>
```suggestion
    <param from="$(var param_path)"/>
```

2024-09-02 04:58 UTC, isamu-takagi requested changes
Since the parameter file is not installed, the `data_files` in `setup.py` should be as follows:
```
    data_files=[
        ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
        (f"share/{package_name}", ["package.xml"]),
        (f"share/{package_name}/launch", [f"launch/{package_name}.launch.xml"]),
        (f"share/{package_name}/config", [f"config/{package_name}.param.yaml"]),
    ],
```

2024-09-02 07:23 UTC, prakash-kannaiah commented
> Since the parameter file is not installed, the `data_files` in `setup.py` should be as follows:
> 
> ```
>     data_files=[
>         ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
>         (f"share/{package_name}", ["package.xml"]),
>         (f"share/{package_name}/launch", [f"launch/{package_name}.launch.xml"]),
>         (f"share/{package_name}/config", [f"config/{package_name}.param.yaml"]),
>     ],
> ```

2024-09-02 08:05 UTC, isamu-takagi approved these changes
LGTM

2025-02-04 16:05 UTC, xmfcx commented
@prakash-kannaiah could you rebase and resolve the conflicts?

2025-09-30 15:18 UTC, closed without merging