perf(autoware_universe_utils): introduce managed transform buffer with implicitly defined listener type
autowarefoundation/autoware_universe pull request #9197
Opened 2024-10-30 08:02 UTC by amadeuszsz

## Description

See parent issue.

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/5385

## How was this PR tested?

See parent issue.

## Notes for reviewers

None.

## Interface changes

- `has_static_tf_only` parameter is not necessary anymore.
- `getTransform` now has form `getTransform<typename T>` (`geometry_msgs::msg::TransformStamped`, `tf2::Transform`, `Eigen::Matrix4f`).
- `getTransform` returns `std::optional`.

## Effects on system behavior

See parent issue.

2025-03-06 04:11 UTC, knzo25 commented on perception/autoware_ground_segmentation/README.md
> -| `input_frame`        | string | " "           | input frame id                        |
Not really for this PR, but
" " does not evaluate as empty, so I think it goes against its apparent objective
https://github.com/autowarefoundation/autoware.universe/blob/b3caa5cea50a6747ff77f96786396b3176840a74/sensing/autoware_pointcloud_preprocessor/src/filter.cpp#L274

@badai-nguyen  what do you think?

2025-04-02 07:38 UTC, badai-nguyen commented on perception/autoware_ground_segmentation/README.md
> -| `input_frame`        | string | " "           | input frame id                        |
@knzo25 I'm so sorry, I missed your mention here let have a look.

2025-04-08 00:54 UTC, knzo25 commented
@amadeuszsz 
Additional nodes have been added since this PR was opened. Can you make them use the managed transform?

2025-04-08 01:45 UTC, knzo25 requested changes
@amadeuszsz 
I am sorry, but it seems we will not be able to merge this as is.
With the taxi,we still have a rear lidar configured, even though in 99% of the cases, the cloud will be empty.

The concat waits for the rear cloud, and accepts it even when it is empty. If it does not receive it, it will publish the cloud much later, effectively publishing it 1 frame off, so we need to publish it.

I checked the base autoware and this PR + the awf/managed_transform and could confirm this phenomena.

An easy fix would be to consider a pointcloud transform successful no matter what frames are being transformed when the pointcloud is empty

2025-04-08 03:58 UTC, amadeuszsz commented
> @amadeuszsz I am sorry, but it seems we will not be able to merge this as is. With the taxi,we still have a rear lidar configured, even though in 99% of the cases, the cloud will be empty.
> 
> The concat waits for the rear cloud, and accepts it even when it is empty. If it does not receive it, it will publish the cloud much later, effectively publishing it 1 frame off, so we need to publish it.
> 
> I checked the base autoware and this PR + the awf/managed_transform and could confirm this phenomena.
> 
> An easy fix would be to consider a pointcloud transform successful no matter what frames are being transformed when the pointcloud is empty

Thanks for review! Empty cloud is not an error anymore. Also updated latest node.

2025-04-08 04:35 UTC, knzo25 commented
@amadeuszsz 

 - How do you plan to add this to autoware? 
 - Since you have added all the other universe nodes, can you add the one for the cuda pointcloud preprocessor ?
 - Can the camel case repo name cause issues for the build farm?

2025-04-08 04:35 UTC, knzo25 requested changes
@amadeuszsz
Confirmed that it works as expected, including the previous problematic case. However:

 - How do you plan to add this to autoware?
 - Since you have added all the other universe nodes, can you add the one for the cuda pointcloud preprocessor ?
 - Can the camel case repo name cause issues for the build farm?

2025-04-08 04:54 UTC, amadeuszsz commented
> @amadeuszsz Confirmed that it works as expected, including the previous problematic case. However:
> 
> * How do you plan to add this to autoware?

PR https://github.com/autowarefoundation/autoware/pull/5611 already awaiting.

> * Since you have added all the other universe nodes, can you add the one for the cuda pointcloud preprocessor ?

This PR targets only `autoware_pointcloud_preprocessor` and other packages can be addressed in separate PRs. Only test branch applied managed TF buffer on all the nodes for testing purposes.

> * Can the camel case repo name cause issues for the build farm?

I don't think so. `snake_case` is required for `autoware_xyz` packages [only](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/languages/cpp/#use-lower-snake-case-for-function-names-required-partially-automated). However, if you think it would be better to refactor it now, we can do it 🥲

2025-04-08 05:08 UTC, knzo25 approved these changes
LGTM !
Can you get approval for the autoware PR before merging this one?
That way we can merge both with minimal time difference

2025-04-08 05:09 UTC, knzo25 commented
PS: when both PRs are merged remind me to apply the managed transform to the cuda preprocessor. I need to also add the polling subscriber so I can do both in one seating

2025-04-08 05:11 UTC, knzo25 commented
@badai-nguyen  @soblin 
Can you take a look a this please ? :pray:

2025-04-08 05:13 UTC, amadeuszsz commented
I will also address `autoware_core` since those minimal nodes use deprecated `managed_transform_buffer` from `autoware_utils`.

2025-04-08 05:16 UTC, soblin approved these changes

2025-04-08 08:52 UTC, badai-nguyen commented
@amadeuszsz 
I think a refactor PR to remove `has_static_tf_only` from autoware_launch is needed such as
https://github.com/autowarefoundation/autoware_launch/blob/0b9caea24347f57a062f29b3524caef73a3295ff/sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml#L4

2025-04-08 08:53 UTC, amadeuszsz commented
> @amadeuszsz I think a refactor PR to remove `has_static_tf_only` from autoware_launch is needed such as https://github.com/autowarefoundation/autoware_launch/blob/0b9caea24347f57a062f29b3524caef73a3295ff/sensor_kit/awsim_labs_sensor_kit_launch/awsim_labs_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml#L4

@badai-nguyen 
It's already addressed in https://github.com/autowarefoundation/autoware_launch/pull/1393

2025-04-08 09:07 UTC, knzo25 commented
@amadeuszsz 
Just to make it faster to get merged.
Can you list all the related PRs and issues ad the beginning of each PR?

2025-04-08 12:08 UTC, badai-nguyen approved these changes
LGTM regarding `compare_map_segmentation` and `ground_segmentation`!

2025-04-08 12:18 UTC, badai-nguyen commented on sensing/autoware_pointcloud_preprocessor/src/concatenate_data/combine_cloud_handler.cpp
@amadeuszsz
Just a question, before change, `managed_tf_buffer_->transform_pointcloud`'s `has_static_only=false` as here https://github.com/autowarefoundation/autoware_launch/blob/d32ac7200f26685d9c00e01d6ca57d69cfc8ec69/sensor_kit/awsim_sensor_kit_launch/awsim_sensor_kit_launch/config/concatenate_and_time_sync_node.param.yaml#L4.
It mean that 
`managed_tf_buffer_->transform_pointcloud` will use latest timestamp for transformed but this you change to pointcloud's timestamp. 
Is this intentional?

2025-04-08 14:23 UTC, amadeuszsz commented on sensing/autoware_pointcloud_preprocessor/src/concatenate_data/combine_cloud_handler.cpp
@badai-nguyen 
Yes. Before I hardcoded time as `now()` without deeper investigation.  In old `autoware_pointcloud_preprocessor` implementation, we mostly used [pcl_ros](https://github.com/autowarefoundation/autoware_universe/blob/9bb228fe5b7fa4c6edb47e4713c73489a02366e1/sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp#L234), which takes stamp from [msg](https://github.com/ros-perception/perception_pcl/blob/humble/pcl_ros/src/transforms.cpp#L74-L77). However, our implementation got refactor, so now it is difficult to decide which stamp should we use. To reproduce latest behavior, we should put `now()` here, but I assumed it was a mistake forced by previous `managed_transform_buffer` implementation. 
@vividf as you understand inner algorithm well, could you please tell us please which stamp (`now()` or from input cloud msg) should we use?

2025-04-09 02:30 UTC, vividf commented on sensing/autoware_pointcloud_preprocessor/src/concatenate_data/combine_cloud_handler.cpp
@amadeuszsz I think either approach is fine—using now() or the message timestamp—since the transform from LiDAR to base_link is always the same. Personally, I prefer using the message timestamp since it makes more sense as we're applying the transformation to that specific point cloud.

2025-04-11 09:00 UTC, merged